export const mockmenu =[
    {
        "id":"5129710648430592",
        "name":"sys",
        "level":1,
        "type":0,
        "title":"系统管理",
        "path":"/sys",
        "component":"Main",
        "icon":"ios-settings",
        "sortOrder":1,
        "status":0,
        "url":"/a",
        "children":[
            {
                "id":"5129710648430592",
                "name":"tellermanager",
                "level":1,
                "type":0,
                "title":"用戶管理",
                "path":"teller",
                "component":"coframe/teller/tellerManage",
                "icon":"ios-settings",
                "sortOrder":1,
                "status":0,
                "url":"",
                "permTypes":null
            },
            {
                "id":"512dddeee648430593",
                "name":"menumanager",
                "level":1,
                "type":0,
                "title":"菜单管理",
                "path":"menumanager",
                "component":"coframe/menu/menumanager",
                "icon":"ios-settings",
                "sortOrder":2,
                "status":0,
                "url":"",
                "permTypes":null
            },
            {
                "id":"512dddeee648430594",
                "name":"rolemanager",
                "level":1,
                "type":0,
                "title":"角色管理",
                "path":"rolemanager",
                "component":"coframe/role/roleManager",
                "icon":"ios-people",
                "sortOrder":3,
                "status":0,
                "url":"",
                "permTypes":null
            }
        ],
        "permTypes":null,
        "expand":true,
        "checked":false,
        "selected":false
    }
]